<?php
/**
 * Created by PhpStorm.
 * User: jan
 * Date: 28.5.18
 * Time: 18:38
 */

namespace MauticPlugin\MauticVtigerCrmBundle\Vtiger\Model;

/**
 * Class ModuleFieldInfo
 *
 * @see
 * public 'name' => string 'salutationtype' (length=14)
 * public 'label' => string 'Salutation' (length=10)
 * public 'mandatory' => boolean false
 * public 'type' =>
 * object(stdClass)[890]
 * ...
 * public 'isunique' => boolean false
 * public 'nullable' => boolean true
 * public 'editable' => boolean true
 * public 'default' => string '' (length=0)
 *
 * @package MauticPlugin\MauticVtigerCrmBundle\Vtiger\Model
 */
class ModuleFieldInfo
{
    /** @var string */
    private $name;
    /** @var string */
    private $label;
    /** @var bool */
    private $mandatory;
    /** @var mixed */
    private $type;
    /** @var bool */
    private $isUnique;
    /** @var bool */
    private $nullable;
    /** @var bool */
    private $editable;
    /** @var String */
    private $default;

    public function __construct(\stdClass $data)
    {
        $this->label = $data->label;
        $this->name = $data->name;
        $this->mandatory = $data->mandatory;
        $this->type = $data->type;
        if (!isset($data->isunique) && in_array('autogenerated', (array) $data->type)) {
            $this->isUnique = true;
        } else {
            $this->isUnique = $data->isunique;
        }
        $this->nullable = $data->nullable;
        $this->editable = $data->editable;
        $this->default = $data->default;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @return string
     */
    public function getLabel(): string
    {
        return $this->label;
    }

    /**
     * @return bool
     */
    public function isMandatory(): bool
    {
        return $this->mandatory;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @return bool
     */
    public function isUnique(): bool
    {
        return $this->isUnique;
    }

    /**
     * @return bool
     */
    public function isNullable(): bool
    {
        return $this->nullable;
    }

    /**
     * @return bool
     */
    public function isEditable(): bool
    {
        return $this->editable;
    }

    /**
     * @return String
     */
    public function getDefault(): String
    {
        return $this->default;
    }

}